name: movie_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path:
  http: 
  dio: ^4.0.0
  device_info:
  readmore: ^2.0.0
  carousel_slider: ^3.0.0
  shared_preferences: ^2.0.0
  syncfusion_flutter_datagrid: 
  flutter_svg_provider: ^0.1.9
  cached_network_image: ^3.0.0
  curved_navigation_bar: ^0.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4


flutter_native_splash:
  android: true
  ios: true
  web: true
  background_image: "assets/images/Splesh Screen.jpg"
  image: assets/logos/Logo.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/ 
    - assets/video/ 
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

